import React from 'react'
import type { Metadata } from 'next'
import './globals.scss'
import { montserrat, phonk_sans } from '@/fonts'
import StoreProvider from '@/app/store-provider'
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${montserrat.variable} ${phonk_sans.variable} antialiased`}
            >
                <ToastContainer position="top-right" />
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    )
}
